// Generated by CoffeeScript 1.6.3
var page, webserverTest;

page = require("webpage").create();

webserverTest = require("webserver").create();

webserverTest.listen(8083, function(request, response) {
  if (request.url === "/ping.html") {
    response.statusCode = 200;
    response.write("slimerjs server is listening\n");
    return response.close();
  } else {
    return page.open("../local-copies/html-converted/" + request.queryString + "/" + request.queryString + ".html").then(function(status) {
      if (status === "success") {
        console.log(request.queryString);
        console.log(request.path);
        response.statusCode = 200;
        response.write("page loaded by slimerjs");
        response.close();
      } else {
        response.statusCode = 500;
        response.write("page could not be found by slimerjs");
        response.close();
        console.log("page could not be found by slimerjs");
      }
      return page.close();
    });
  }
});
